//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustOneCart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JustOneCartEntities1 : DbContext
    {
        public JustOneCartEntities1()
            : base("name=JustOneCartEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductOrder> ProductOrders { get; set; }
        public virtual DbSet<Aisle> Aisles { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<ProductDailyRequest> ProductDailyRequests { get; set; }
        public virtual DbSet<ProductPurchaseLog> ProductPurchaseLogs { get; set; }
        public virtual DbSet<Side> Sides { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<user1> users1 { get; set; }
    }
}
